export const CAPABILITIES = Object.freeze({
  SEARCH: "SEARCH",
  PRICE_CHECK: "PRICE_CHECK",
  SUPPLIER_DISCOVERY: "SUPPLIER_DISCOVERY",
  BUYER_DISCOVERY: "BUYER_DISCOVERY",
  PRODUCT_LOOKUP: "PRODUCT_LOOKUP",
  AVAILABILITY: "AVAILABILITY",
  IDENTITY: "IDENTITY",
  VERIFICATION: "VERIFICATION",
  NEGOTIATION: "NEGOTIATION",
  QUOTE: "QUOTE",
  ORDER: "ORDER",
  PAYMENT: "PAYMENT",
  DEPLOY: "DEPLOY",
  DOMAIN_REGISTER: "DOMAIN_REGISTER",
  DNS: "DNS",
  HOSTING: "HOSTING",
  STORAGE: "STORAGE",
  NOTIFICATION: "NOTIFICATION",
});

export const CAPABILITY_GROUPS = Object.freeze({
  DISCOVERY: [
    CAPABILITIES.SEARCH,
    CAPABILITIES.PRICE_CHECK,
    CAPABILITIES.SUPPLIER_DISCOVERY,
    CAPABILITIES.BUYER_DISCOVERY,
    CAPABILITIES.PRODUCT_LOOKUP,
    CAPABILITIES.AVAILABILITY,
  ],

  TRUST: [
    CAPABILITIES.IDENTITY,
    CAPABILITIES.VERIFICATION,
  ],

  COMMERCIAL: [
    CAPABILITIES.NEGOTIATION,
    CAPABILITIES.QUOTE,
    CAPABILITIES.ORDER,
    CAPABILITIES.PAYMENT,
  ],

  INFRASTRUCTURE: [
    CAPABILITIES.DEPLOY,
    CAPABILITIES.DOMAIN_REGISTER,
    CAPABILITIES.DNS,
    CAPABILITIES.HOSTING,
    CAPABILITIES.STORAGE,
    CAPABILITIES.NOTIFICATION,
  ],
});

export function isCapability(value) {
  return Object.values(CAPABILITIES).includes(value);
}
